//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libcis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContent
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ServiceId { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public int CustomerId { get; set; }
        public short Viewed { get; set; }
    }
}
